version: '2'
volumes:
  db:
  staging:
  static:
  store:
services:
  django:
    image: uwaedu/mytardis_django
    ports:
      - '127.0.0.1:8000:8000'
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_ADMINS=[('Dean Taylor','dean.taylor@uwa.edu.au'),]
      - DJANGO_ALLOWED_HOSTS=['localhost',]
      - DJANGO_EMAIL_SUBJECT_PREFIX="[TruDat@UWA_Dev]:"
      - DJANGO_DATETIME_FORMAT='jS F Y H:i'
      - DJANGO_DATE_FORMAT='jS F Y'
      - DJANGO_DEFAULT_FROM_EMAIL='donotreply-trudat@uwa.edu.au'
      - GUNICORN_WORKER_CLASS=gevent
      - MYTARDIS_BIOFORMATS_ENABLE=True
      - MYTARDIS_SITE_TITLE=TruDat@UWA_Dev
      - MYTARDIS_RAPID_CONNECT_ENABLED=False
      - POSTGRES_PASSWORD=postgres
    links:
      - db
      - rabbitmq
    volumes:
      - staging:/usr/src/app/var/staging
      - static:/usr/src/app/static
      - store:/usr/src/app/var/store
      - ./src/nifcert/:/usr/src/app/nifcert/
      - ./src/nifcert/docs/settings.d/nifcert.py:/usr/src/app/settings.d/nifcert.py
  celery:
    image: uwaedu/mytardis_django
    command: --loglevel=INFO --autoreload
    environment:
      - CELERY_ENABLE=True
      - MYTARDIS_BIOFORMATS_FILTER_ENABLE=False
      - POSTGRES_PASSWORD=postgres
    links:
      - db
      - rabbitmq
    volumes:
      - staging:/usr/src/app/var/staging
      - store:/usr/src/app/var/store
      - ./src/nifcert/:/usr/src/app/nifcert/
      - ./src/nifcert/docs/settings.d/nifcert.py:/usr/src/app/settings.d/nifcert.py
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums --locale=en_US.utf8
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3
